/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ConcoursDao;
import dao.ExerciceDao;
import dao.MotDao;
import entities.Concours;
import entities.Eleve;
import entities.Exercice;
import entities.Mot;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author chris dany
 */
public class Exo extends javax.swing.JFrame {

    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private static final String SUCCES = "correct";
    private static final String ECHEC = "incorrect";
    private List<Exercice> exercices = new ArrayList<>();
    private Concours concours;

    private int exo = 1;
    private int reussite = 0;
    private Eleve eleve;

    public Exo() {
        initComponents();
        jtfLINGALA.setEditable(false);
        jtfSW.setEditable(false);
    }

    public Exo(Eleve e, Exo exo, int index) {
        this.exo = index;
        this.eleve = e;
        initComponents();
        jtfLINGALA.setEditable(false);
        jtfSW.setEditable(false);
        concours = new Concours(eleve, sdf.format(new Date()));

    }

    public int getExo() {
        return exo;
    }

    public void setExo(int exo) {
        this.exo = exo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfFR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfEN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfLINGALA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfSW = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercice : "+exo+" FRANCAIS - ANGLAIS"));

        jLabel1.setText("Francais : ");

        jLabel2.setText("Anglais : ");

        jLabel3.setText("Lingala : ");

        jLabel4.setText("Swahili : ");

        jButton1.setText("Suivant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfEN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfLINGALA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfFR, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfSW, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfLINGALA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfSW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            if (!jtfFR.getText().isEmpty()) {
                String motFr = jtfFR.getText();
                Mot mot = MotDao.getMotByFr(motFr);
                if (mot.getFrancais() != null) {
                    if (exo <= 4) {
//anglais
                        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercice : " + exo + " | FRANCAIS - ANGLAIS"));
                        jtfLINGALA.setEditable(false);
                        jtfSW.setEditable(false);
                        jtfEN.setEditable(true);

                        if (!jtfEN.getText().isEmpty()) {
                            if (mot.getAnglais().toLowerCase().equals(jtfEN.getText().toLowerCase())) {
                                JOptionPane.showMessageDialog(this, "OK");
                                reussite++;
                                Exercice exercice = new Exercice(mot.getId(), concours, SUCCES);
                                exercices.add(exercice);
                                //Exercice exo = ExerciceDao.ajouterExercice(eleve.getId(), mot.getId(), SUCCES, sdf.format(new Date()));
                                jtfEN.setText("");
                                jtfFR.setText("");
                                jtfSW.setText("");
                                jtfLINGALA.setText("");
                            } else {
                                JOptionPane.showMessageDialog(this, "Echec. Le mot exact est '" + mot.getAnglais() + "'");
                                Exercice exercice = new Exercice(mot.getId(), concours, ECHEC);
                                exercices.add(exercice);
                                //Exercice exo = ExerciceDao.ajouterExercice(eleve.getId(), mot.getId(), ECHEC, sdf.format(new Date()));
                                jtfEN.setText("");
                                jtfFR.setText("");
                                jtfSW.setText("");
                                jtfLINGALA.setText("");
                            }
                            exo++;
                        } else {
                            JOptionPane.showMessageDialog(this, "Entrez le mot en anglais svp");
                        }

                    }
                    if (exo > 4 && exo < 9) {
//swahili
                        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercice : " + exo + " | FRANCAIS - SWAHILI"));
                        jtfLINGALA.setEditable(false);
                        jtfEN.setEditable(false);
                        jtfSW.setEditable(true);

                        if (!jtfSW.getText().isEmpty()) {
                            if (mot.getSwahili().toLowerCase().equals(jtfSW.getText().toLowerCase())) {
                                JOptionPane.showMessageDialog(this, "OK");
                                reussite++;
                                Exercice exercice = new Exercice(mot.getId(), concours, SUCCES);
                                exercices.add(exercice);
                                // Exercice exo = ExerciceDao.ajouterExercice(eleve.getId(), mot.getId(), SUCCES, sdf.format(new Date()));
                                jtfEN.setText("");
                                jtfFR.setText("");
                                jtfSW.setText("");
                                jtfLINGALA.setText("");
                            } else {
                                JOptionPane.showMessageDialog(this, "Echec. Le mot exact est '" + mot.getSwahili() + "'");
                                Exercice exercice = new Exercice(mot.getId(), concours, ECHEC);
                                exercices.add(exercice);
                                //Exercice exo = ExerciceDao.ajouterExercice(eleve.getId(), mot.getId(), ECHEC, sdf.format(new Date()));
                                jtfEN.setText("");
                                jtfFR.setText("");
                                jtfSW.setText("");
                                jtfLINGALA.setText("");
                            }
                            exo++;
                        } else {
                            JOptionPane.showMessageDialog(this, "Entrez le mot en swahili svp");
                        }
                    }
                    if (exo > 8 && exo < 13) {
//lingala
                        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercice : " + exo + " | FRANCAIS - LINGALA"));

                        jtfSW.setEditable(false);
                        jtfEN.setEditable(false);
                        jtfLINGALA.setEditable(true);

                        if (!jtfLINGALA.getText().isEmpty()) {
                            if (mot.getLingala().toLowerCase().equals(jtfLINGALA.getText().toLowerCase())) {
                                JOptionPane.showMessageDialog(this, "OK");
                                reussite++;
                                Exercice exercice = new Exercice(mot.getId(), concours, SUCCES);
                                exercices.add(exercice);
                                // Exercice exo = ExerciceDao.ajouterExercice(eleve.getId(), mot.getId(), SUCCES, sdf.format(new Date()));
                                jtfEN.setText("");
                                jtfFR.setText("");
                                jtfSW.setText("");
                                jtfLINGALA.setText("");
                            } else {
                                JOptionPane.showMessageDialog(this, "Echec. Le mot exact est '" + mot.getLingala() + "'");
                                Exercice exercice = new Exercice(mot.getId(), concours, ECHEC);
                                exercices.add(exercice);
                                //Exercice exo = ExerciceDao.ajouterExercice(eleve.getId(), mot.getId(), ECHEC, sdf.format(new Date()));
                                jtfEN.setText("");
                                jtfFR.setText("");
                                jtfSW.setText("");
                                jtfLINGALA.setText("");
                            }
                            exo++;
                        } else {
                            JOptionPane.showMessageDialog(this, "Entrez le mot en lingala svp");
                        }
                    }
                    if (exo > 12) {
                        System.out.println("@@@@@@@@@@@@@@");
                        Concours c = ConcoursDao.ajouterConcours(eleve.getId(), sdf.format(new Date()), reussite);
                        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
                        for (Exercice exercice : exercices) {
                            ExerciceDao.ajouterExercice(c.getId(), exercice.getIdMot(), exercice.getResultat());
                        }
                        JOptionPane.showMessageDialog(this, "Fin de l'exercice! Votre score est de " + reussite + "/12");
                        setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ce mot n'existe pas dans la bdd");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Entrez le mot en francais svp");

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfEN;
    private javax.swing.JTextField jtfFR;
    private javax.swing.JTextField jtfLINGALA;
    private javax.swing.JTextField jtfSW;
    // End of variables declaration//GEN-END:variables
}
