/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.MotDao;
import entities.Mot;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris dany
 */
public class GererMotui extends javax.swing.JFrame {

    DefaultTableModel model;
    private Boolean editMode = false;
    private List<Mot> allMot = MotDao.allMots();
    private int selectedIndex = 0;

    /**
     * Creates new form AjouterMot
     */
    public GererMotui() throws SQLException {
        initComponents();
        model = (DefaultTableModel) jTableMot.getModel();
        loadMot();
        deactivateFields();
    }

    public void loadMot() throws SQLException {
        model.setNumRows(0);
        allMot = MotDao.allMots();
        for (Mot mot : allMot) {
            model.addRow(new Object[]{mot.getFrancais(), mot.getSwahili(), mot.getLingala(), mot.getAnglais()});

        }
    }

    public void deactivateFields() {
        jTextFieldMotEn.setEnabled(false);
        jTextFieldMotFr.setEnabled(false);
        jTextFieldMotSw.setEnabled(false);
        jTextFieldMotLi.setEnabled(false);
        jButtonMotEnregistrer.setEnabled(false);

    }

    public void activateFields() {
        jTextFieldMotEn.setEnabled(true);
        jTextFieldMotFr.setEnabled(true);
        jTextFieldMotSw.setEnabled(true);
        jTextFieldMotLi.setEnabled(true);
        jButtonMotEnregistrer.setEnabled(true);

    }

    public void emptyFields() {
        jTextFieldMotEn.setText("");
        jTextFieldMotFr.setText("");
        jTextFieldMotSw.setText("");
        jTextFieldMotLi.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMotFr = new javax.swing.JTextField();
        jTextFieldMotLi = new javax.swing.JTextField();
        jTextFieldMotEn = new javax.swing.JTextField();
        jTextFieldMotSw = new javax.swing.JTextField();
        jButtonMotEnregistrer = new javax.swing.JButton();
        jButtonMotAjouter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMot = new javax.swing.JTable();
        jButtonMotModifier = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un mot"));

        jLabel1.setText("Francais");

        jLabel2.setText("Swahili");

        jLabel3.setText("Lingala");

        jLabel4.setText("Anglais");

        jTextFieldMotSw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotSwActionPerformed(evt);
            }
        });

        jButtonMotEnregistrer.setText("Enregistrer");
        jButtonMotEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotEnregistrerActionPerformed(evt);
            }
        });

        jButtonMotAjouter.setText("Ajouter");
        jButtonMotAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotAjouterActionPerformed(evt);
            }
        });

        jTableMot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Francais", "Swahili", "Lingala", "Anglais"
            }
        ));
        jScrollPane1.setViewportView(jTableMot);

        jButtonMotModifier.setText("Modifier");
        jButtonMotModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotModifierActionPerformed(evt);
            }
        });

        jLabelMessage.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldMotEn, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jTextFieldMotLi, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jTextFieldMotFr)
                    .addComponent(jTextFieldMotSw, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jButtonMotEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMotAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMotModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMotFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldMotSw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(jTextFieldMotLi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldMotEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMotEnregistrer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMotAjouter)
                    .addComponent(jButtonMotModifier))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMotSwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotSwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotSwActionPerformed

    private void jButtonMotEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotEnregistrerActionPerformed
        if (editMode == false) {
            try {
                // TODO add your handling code here:
                System.out.println("hhhhhhhhhhhh");
                if (jTextFieldMotFr.getText().isEmpty() | jTextFieldMotSw.getText().isEmpty() | jTextFieldMotEn.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires!!!");
                } else {
                    MotDao.ajouterMot(jTextFieldMotFr.getText(), jTextFieldMotSw.getText(), jTextFieldMotLi.getText(), jTextFieldMotEn.getText());
                    loadMot();
                    jLabelMessage.setText("Enregistrement effectué avec succès");
                }
            } catch (SQLException ex) {
                Logger.getLogger(GererMotui.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("8888888888888888");
            try {
                // avoir id mot methode
                //
                Mot selectedMot = allMot.get(selectedIndex);
                if (jTextFieldMotFr.getText().isEmpty() | jTextFieldMotSw.getText().isEmpty() | jTextFieldMotEn.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires!!!");
                } else {
                    MotDao.modiferMot(selectedMot.getId(), jTextFieldMotFr.getText(), jTextFieldMotSw.getText(), jTextFieldMotLi.getText(), jTextFieldMotEn.getText());
                    loadMot();
                    jLabelMessage.setText("Modification effectué avec succès");
                }
            } catch (SQLException ex) {
                Logger.getLogger(GererMotui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        emptyFields();
        deactivateFields();
    }//GEN-LAST:event_jButtonMotEnregistrerActionPerformed

    private void jButtonMotAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotAjouterActionPerformed
        // TODO add your handling code here:
        jLabelMessage.setText("");
        emptyFields();
        editMode = false;
        activateFields();
    }//GEN-LAST:event_jButtonMotAjouterActionPerformed

    private void jButtonMotModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotModifierActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableMot.getSelectedRow();
        if (selectedRow != -1) {
            jLabelMessage.setText("");
            editMode = true;
            activateFields();
            //int selectedRow = jTableMot.getSelectedRow();
            selectedIndex = selectedRow;
            // int selectedColumn = jTableMot.getSelectedColumn();
            jTextFieldMotFr.setText((String) jTableMot.getValueAt(selectedRow, 0));
            jTextFieldMotSw.setText((String) jTableMot.getValueAt(selectedRow, 1));
            jTextFieldMotLi.setText((String) jTableMot.getValueAt(selectedRow, 2));
            jTextFieldMotEn.setText((String) jTableMot.getValueAt(selectedRow, 3));
        } else {
            JOptionPane.showMessageDialog(this, "Selectionnez une ligne svp!!!");
        }
    }//GEN-LAST:event_jButtonMotModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererMotui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererMotui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererMotui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererMotui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GererMotui().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GererMotui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMotAjouter;
    private javax.swing.JButton jButtonMotEnregistrer;
    private javax.swing.JButton jButtonMotModifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMot;
    private javax.swing.JTextField jTextFieldMotEn;
    private javax.swing.JTextField jTextFieldMotFr;
    private javax.swing.JTextField jTextFieldMotLi;
    private javax.swing.JTextField jTextFieldMotSw;
    // End of variables declaration//GEN-END:variables
}
